# ----------------------------
# Makefile Options
# ----------------------------

NAME = Ground
ICON = icon.png
DESCRIPTION = "Ground Runner Demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
