# ----------------------------
# Makefile Options
# ----------------------------

NAME = tilegame
ICON = icon.png
DESCRIPTION = "A simple tile matching game"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------
# Include CEdev default Makefile
# ----------------------------

include $(shell cedev-config --makefile)
