# ----------------------------
# Makefile Options
# ----------------------------

NAME = pong
ICON = icon.png
DESCRIPTION = "pong by mumbojum"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
