# ----------------------------
# Makefile Options
# ----------------------------

NAME = picview
ICON = icon.png
DESCRIPTION = "pic viewer demo"
COMPRESSED = NO

CFLAGS = -Wall -Wextra -Oz
CXXFLAGS = -Wall -Wextra -Oz

# ----------------------------

include $(shell cedev-config --makefile)
